name: Fix dist-tags

on: workflow_dispatch

jobs:
  fix-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
      - name: Restore latest dist-tag
        run: npm dist-tag add @janiscommerce/app-device-info@1.2.0 latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Set beta dist-tag
        run: npm dist-tag add @janiscommerce/app-device-info@1.3.0-beta.0 beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
